#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo ' Styling, testing and building your project before commiting'

# Check Prettier
npm run check-format ||
(
    echo 'Prettier check Failed. Run npm run format, add chenges and try commit again';
    false;
)

# Check ESLint
npm run check-lint ||
(
    echo 'ESLint check Failed. Make the required changes listed above, add changes and try commit again';
    false;
)

# Check tsconfig
npm run check-types ||
(
    echo 'Failed type check. Make the changes required above, add changes and try commit again';
    false;
)

npm run build ||
(
    echo 'Your build failed, view the errors above';
    false;
)

echo 'Success Commit';